# Generated by Django 5.1.1 on 2025-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_careercategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerpath",
            name="category",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Commerce", "Commerce"),
                    ("Arts", "Arts"),
                    ("Vocational", "Vocational"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
