# Generated by Django 5.1.1 on 2025-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0004_careerpath_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerpath",
            name="image_url",
        ),
        migrations.AddField(
            model_name="careerpath",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="career_images/"),
        ),
    ]
