# Generated by Django 5.1.1 on 2025-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0005_remove_careerpath_image_url_careerpath_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("subject", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
