# Generated by Django 5.1.1 on 2025-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0007_careerdetail_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerdetail",
            name="skills_required",
        ),
    ]
